
# Signup request
POST http://localhost:8788/api/email-signup HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "captchaToken": "12345"
}

###

# Confirmation request
GET http://localhost:8788/api/confirm-email-signup/123 HTTP/1.1